<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Irfan" failures="1" tests="7" name="api.test.CustomerTests" time="48.874" errors="0" timestamp="2024-11-13T13:15:43 IST" skipped="2">
  <testcase classname="api.test.CustomerTests" name="runAllTestsTenTimes" time="38.031"/>
  <testcase classname="api.test.CustomerTests" name="testCreateCustomer" time="2.197">
    <failure message="Status code is not as expected expected [200] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status code is not as expected expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.test.CustomerTests.testCreateCustomer(CustomerTests.java:88)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCreateCustomer -->
  <testcase classname="api.test.CustomerTests" name="testAddWalletHistory" time="0.001">
    <skipped/>
  </testcase> <!-- testAddWalletHistory -->
  <testcase classname="api.test.CustomerTests" name="testAddCustomerAddress" time="0.001">
    <skipped/>
  </testcase> <!-- testAddCustomerAddress -->
  <testcase classname="api.test.CustomerTests" name="testGetCustomerAddressByCustomerId" time="3.089"/>
  <testcase classname="api.test.CustomerTests" name="testPlaceOrder" time="3.259"/>
  <testcase classname="api.test.CustomerTests" name="testPlaceOrderAlternative" time="2.296"/>
</testsuite> <!-- api.test.CustomerTests -->
